### ISSUE TITLE
Monthly Newsletter newsgathering 

### ISSUE THREAD

**Issue by admataz** [lnug/feedback#100]
Every month we send out a newsletter or two to all our members. If you have something to add or share that you want to get out there - put it here.

Anything it node.js related  - releases, node.js in the wild, meetups, blog post links.. stories, jokes, projects...  only one thing -  keep it London, this is LNUG, not SF.

Oh, and it's not a jobs board, so don't even try.

**Comment by iancrowther** [comment]
http://node.green/

**Comment by iancrowther** [comment]
london.nodeconf.com

x2 free tickets to raffle and discount code "nodeconf-london-2016-lnug"
