### ISSUE TITLE
Monthly Newsletter newsgathering - May 2016

### ISSUE THREAD

**Issue by admataz** [lnug/feedback#102]
Every month we send out a newsletter or two to all our members. If you have something to add or share that you want to get out there - put it here.

Anything it node.js related - releases, node.js in the wild, meetups, blog post links.. stories, jokes, projects... only one thing - keep it London, this is LNUG, not SF.

Oh, and it's not a jobs board, so don't even try.

**Comment by admataz** [comment]
@lnug/organisers no news this month?

**Comment by alanshaw** [comment]
Node.js 6 was released
All the ES2015 - http://node.green/
