### ISSUE TITLE
Alternative to pizza?

### ISSUE THREAD

**Issue by clarkie** [lnug/feedback#103]
I'd like to make this clear, I have no problems with the quantity or quality of the pizzas at LNUG but it has come to my attention that our audience may want a bit of variety. 

I'm just putting this out there for comments / suggestions. 

The requirements are:
- it needs to be shareable
- 'finger food'
- buffet style
- with variety in the selection (e.g. veggie, meat, etc)

... discuss

**Comment by adrianblynch** [comment]
You can't go wrong with sausages! They are both fingerable and shareable and come in both meat 🍖  and non-meat 🍆 versions.

Vote sausages!

**Comment by FLamparski** [comment]
Clearly mini-burritos are the best option.

**Comment by nofootnotes** [comment]
I think burritos are a really good alternative! Pod has been a hit at some of the women's meetups I've been to, though it does require plates/bowls/cutlery. Sushi has also been popular, though I guess that could be expensive.

If you stick with pizza, maybe you could get a couple of vegan ones too?

**Comment by minaorangina** [comment]
This is a great issue!  I think burritos are a good option, and I second Pod too - had that at a couple of tech meetups (plus it's tasty)

**Comment by admataz** [comment]
if anyone want's to reopen this, feel free. Otherwise I'll go on ordering pizza!
