### ISSUE TITLE
Monthly Newsletter newsgathering - September 2016

### ISSUE THREAD

**Issue by admataz** [lnug/feedback#104]
Every month we send out a newsletter or two to all our members. If you have something to add or share that you want to get out there - put it here.

Anything it node.js related - releases, node.js in the wild, meetups, blog post links.. stories, jokes, projects... only one thing - keep it London, this is LNUG, not SF.

Oh, and it's not a jobs board, so don't even try.

**Comment by admataz** [comment]
@lnug/organisers  - please add any news of events, projects, etc so I can add them to the September newsletter

**Comment by achingbrain** [comment]
@admataz Could you please add this to the newsletter?

> NodeBots of London are running their regular meet up on [Sunday 2nd October](https://www.meetup.com/NodeBots-of-London/events/233968335/).
>
> We'll build robots, fly node copters and perhaps inadvertently kickstart the robot apocalypse.
>
> Beginners are more than welcome but places are limited so [sign up soon](https://www.meetup.com/NodeBots-of-London/events/233968335/)!

**Comment by lazlojuly** [comment]
@admataz I have published a blog post on Node.js modules this month: 
[Are Node.js modules singletons?](https://medium.com/@lazlojuly/are-node-js-modules-singletons-764ae97519af)
