### ISSUE TITLE
LNUG Videos 

### ISSUE THREAD

**Issue by bookercodes** [lnug/feedback#105]
Hi, 

I couldn't help but notice that the event hasn't been recorded lately (well, at least if I'm looking at the right [YouTube channel](https://www.youtube.com/channel/UC-qjgj2TnRoI1ZmFFaN3FeQ/videos)!). I work at @Pusher and we currently help a handful of London-based meetups record and transcribe their events by sending a professional videographer to them. [Here's an example recording from Front-End London](https://youtu.be/D9zVXX4TywA), if you're interested.

 Is this something LNUG might be intersted in? If this proposition sounds familiar, it's probably because I sent an email to @iancrowther a couple of weeks ago (had to email Ian personally as[ I couldn't email lnug 😢](https://twitter.com/bookercodes/status/775689337124098052))

**Comment by clarkie** [comment]
Hi Alex,

This sounds very interesting indeed! Ian has been a bit busy recently but feel free to email me andrew.t.clarke at gmail.com

**Comment by alexbooker** [comment]
Will do, @clarkie. Thanks for your prompt response 😄!

**Comment by alexbooker** [comment]
@clarkie OK, I sent you an email. I look forward to hearing from you!

**Comment by jkbits1** [comment]
Hi Alex, thanks for the offer, it would be great to be recording again

**Comment by admataz** [comment]
I think this can be closed and we are underway with help from @pusher. Thanks again @bookercodes
