### ISSUE TITLE
Venue for 2016

### ISSUE THREAD

**Issue by iancrowther** [lnug/feedback#11]
Help us put together a list of venue to contact.

**Comment by ifraixedes** [comment]
Rainmaking Loft London have an [event space](http://www.rainmakingloft.com/london/event-space/) which can ask to use.

Rasthy is the general manager and I can ask directly him.

**Comment by orliesaurus** [comment]
Google Campus

**Comment by iancrowther** [comment]
TechHub

**Comment by iancrowther** [comment]
Facebook

**Comment by iancrowther** [comment]
Github?

**Comment by simonmcmanus** [comment]
what capacity are we looking for?

This appears to be quite a good list of tech friendly venues in London: 

https://docs.google.com/spreadsheet/ccc?key=0AmK8OoJsMrtedGVxQW82NmRiU18tZnkyVHpjSE5fdnc&utm_content=buffer945ee&utm_source=buffer&utm_medium=twitter&utm_campaign=Buffer#gid=0

**Comment by arcturus** [comment]
We could host at mozilla, the only issue is that our space has a capacity for 50 people, and perhaps that's not big enough for this meetup.

**Comment by iancrowther** [comment]
@arcturus thanks for the offer, we may take you up for hackdays..

Capacity should be 200.  We had ~180 at the last event

**Comment by ifraixedes** [comment]
@iancrowther then Rainmaking Loft is discarded people don't fit into.

**Comment by Josh-a-e** [comment]
How about Wayra? It's just off of Tottenham Court Road. I used to be part of a start up there and they've got a great event space.

**Comment by orliesaurus** [comment]
I think they require you to share your attendee's email with them? Maybe I'm wrong...

**Comment by Josh-a-e** [comment]
Having just checked, no they don't :)

**Comment by orliesaurus** [comment]
@Josh-a-e That's a brilliant news then! Thanks for checking :smile:

**Comment by Josh-a-e** [comment]
I've got a meeting there on Wednesday - I'll bring it up and let you know what they say.

**Comment by iancrowther** [comment]
awsm

**Comment by orliesaurus** [comment]
@Josh-a-e how did the meeting go :D ?

**Comment by fmsf** [comment]
if you guys want to do one at paypal/ebay I can get us the space, but it is in richmond

**Comment by ifraixedes** [comment]
@fmst it should be a big change, I guess that the most of the attendees come from London city.

On the other hand for speakers from abroad that they sometimes get the chance to speak would be harder because I guess that the most of the times they visit London city.

**Comment by paulbjensen** [comment]
If anyone knows a contact at Yahoo UK I imagine that they might have the facilities, plus they're a Node.js shop too.

**Comment by orliesaurus** [comment]
@fmsf dont paybal ebay also have an office at TCR ? I been there once but I dunno how much space they got!

**Comment by fmsf** [comment]
Oh yeah we do, I have never been there but I can check if we can host there

**Comment by iancrowther** [comment]
@fmsf would be great if you could

**Comment by Josh-a-e** [comment]
@orliesaurus Hey - had a chat with Wayra: there policy is that if there's enough value to their cohort (which is brand new) they're more than happy to host the event for free, on the conditions they get 2 minutes to introduce themselves (Wayra) and each of the relevant start ups at the beginning (just a line or two about what they're doing with node) - hope this sounds ok with you (I'm sort of assuming that it is).

I know a few of the old cohort were heavy node.js users (including myself), so I've sent a few messages around and requested a mailing list for the new guys so should hopefully get back to you soon with some responses.

They'll only need 3 or 4 interested groups so I doubt this will take too long (I'll push to get some by the middle of the week).

Apologies for not getting back to you sooner!

**Comment by ifraixedes** [comment]
I don't think that they ask for too much,  if the other options don't fit as it could, then I wouldn't say no, because is fair; everybody want something in exchange.
However it's just my opinion.

**Comment by orliesaurus** [comment]
Thanks @Josh-a-e - I appreciate it and it's a fair deal, I would keep this option open!

**Comment by Josh-a-e** [comment]
No worries, that's good to hear. I've found two so far.

**Comment by iancrowther** [comment]
We dont have a venue atm!!

**Comment by simonmcmanus** [comment]
@iancrowther - can we close this now? or is it being kept open for a reason?
