### ISSUE TITLE
New looking to hire/be hired

### ISSUE THREAD

**Issue by adrianblynch** [lnug/feedback#113]
The idea of moving the _to hire/be hired_ to somewhere away from the main stage was cool.

When I read this was happening I worried it would be like a bunch of consultants standing behind tables snatching CVs from any and all developers.

@admataz I think you orchestrating it was right, else it would be a bit awkward.

Might be an idea to add a todo item to the list for each event so someone is allocated to doing that.

**Comment by admataz** [comment]
yes, we need someone to coordinate/orchestrate every meetup to keep it from turning to a recruiter-fest. we're kindof making it up as we go - and trying to keep it real/valuable. I see it as a ramp to getting people used to talking to each other about what they are doing and giving a 30 second pitch - and open some useful conversations/connections

**Comment by orliesaurus** [comment]
Maybe we give everyone a badge (hire-me or hiring) at the start when they check-in ?
I try to send regular newsletters with the - who is hiring/who wants to be hired section - if there's something else we can do to speed up things I'm all ears 👍

**Comment by admataz** [comment]
Our regular  "jobs table" in the break has been a success - closing this
