### ISSUE TITLE
Feedback to LNUG #94 - 27th May 2020

### ISSUE THREAD

**Issue by admataz** [lnug/feedback#117]
If you were at the @LNUGorg meetup last night I’d love to hear some feedback on how it went for attendees. Was it OK? How can we make the remote format work better? I’m  missing the chit-chat and audience participation and feedback! Please respond. in the comments here.

**Comment by phazonoverload** [comment]
Additional thought: I think a midway break is good and allows us to make full use of the features available, while giving time to communicate any changes (like running over)

**Comment by admataz** [comment]
Hey @phazonoverload  - thanks that's all useful feedback

- 2 talks I agree - I kinda knew this already as it's the same pressure in real life meetups. It's a balance - I think the learning here is to get speakers lined up a little earlier. We left it late to confirm - and by then we had more confirmations than we could say no to. 

- getting speakers to stick to time limits is hard in person too - this is an ongoing problem, and again - a balance. Some speakers are better at responding than others. No one wants an interesting talk chopped short by an MC, but we need to be fair to all speakers and attendees. We need to develop our technique here, be more firm, while maintaining respect.

- intro was too long - that's on me - should have saved some points for between talks in those little dead spots. Maybe I'm trying to cover too much in that live moment. 

- 70 is good - would be nice to get more, given there are no real limits

- Recordings! Say it is ok 😟 !! I'm getting requests for the videos

- Notes on the platform - I've also had feedback about the stability/memory issues. My fan was going constantly, and a couple people mentioned it crashing.  From one of our developers: 

> yeah, I was attempting to diagnose that during the meetup :wink: ... I couldn't get very far because it kept locking up on me but there's definitely at least a memory leak in there

So these things go noticed in this community. Would be good if we could pass this on to Remo - and get an idea of their capacity to address feedback (I was also under the impression that Vonage had more of a stake in Remo)

**Comment by phazonoverload** [comment]
Just checked again - was about 80.

Recordings - they seem ok to me! Just downloading and will send you the link once it's done. I think a tiny amount of the last one got chopped off. You can assess. 

Honestly my experience with multi-person video is that it's computationally expensive. Whether it's our APIs, others, Google Meet, Zoom, etc, they all seem to get machines hot. This said, I will pass it on. 

Remo use our APIs in their product, but other than that we have no stake. We assessed options, picked the best one and just pay for a sub to let community members use it. However, we chat with the Remo team occasionally so will bring this (and other feedback I was given) to them. They are super receptive and always making tweaks to improve the product. 

My thoughts around keeping to time is to set expectations with speakers that whether it's going to plan (or not) you will pop in 5 mins from the end to tell them, and then disappear. It's up to them then to come in on-time.

**Comment by phazonoverload** [comment]
Actually I just checked - [the recording](https://drive.google.com/file/d/1CnAZ1FhGbB1VuuVziG_r3kvcqDRZFnSt/view?usp=sharing) capped out at 2 hours so we lost a bit of David's. I think if I had ended and restarted the recording for each speaker it would have worked better - I'll do this next time. Sorry!
