### ISSUE TITLE
Not on a Wednesday?

### ISSUE THREAD

**Issue by Sarkie** [lnug/feedback#12]
Any chance that the day could be Mon, Tue, Thursday,  it is always overloaded for me and my developers on a Wednesday to come along?

Cheers

**Comment by ifraixedes** [comment]
I think, that change should be driven by a poll to the community

**Comment by iancrowther** [comment]
agreed - @ifraixedes want to put one together and tweet it?

**Comment by ifraixedes** [comment]
How do we want to poll? I see that a github issue can be quite messy to count the results, isn't it?

**Comment by iancrowther** [comment]
https://support.google.com/docs/answer/87809?hl=en

**Comment by ifraixedes** [comment]
Done, see [here](https://docs.google.com/forms/d/1wcdj0_kp-gPTr70fzVf_c-dwkumrmsYIgHAOAlZYs1Q/viewform)

Let me know what date we should close the poll to add, then I will tweet about it

**Comment by orliesaurus** [comment]
LNUG has been on a wednesday for about 3 years now

**Comment by ifraixedes** [comment]
Yeah, but I don't feel that a question to the audience can hurt, anyway, I can delete the form. Let me know.

**Comment by orliesaurus** [comment]
No need to delete, how will you gather feedback? do you want me to announce it next month?

**Comment by admataz** [comment]
The problem with this "ask the community approach" with a question like this is that you will never satisfy everyone - and there can never be a unanimous answer to this question that suits everyone's schedules.

I don't disagree in principle with moving to another day in the week, or alternating it, but I think the motivations and decision making should be internal to the organisers -  and I think we should consider carefully before opening up the question to a pseudo vote -  it gives a sense of democracy where there is none - which I think could lead people who's preference didn't win feel like they aren't considered important.

Just my 2p on the issue - of course if the rest of you feel a community poll is valuable, let's just make sure we manage expectations and communicate any changes.

**Comment by ifraixedes** [comment]
A poll does not means that the change must change, it's to know the preferences of the people; I don't like that the poll, google form in this case, is accessible in anonymous form, so somebody could vote as many times as he/she wants, then cheat the results, but to control that people should have a google account, so I wasn't sure if we only want to offer the right to vote to people who owns a google account or they have to create one for only this purpose.

> "ask the community approach" with a question like this is that you will never satisfy everyone 

I agree democracy doesn't satisfy everyone, nonetheless organiser decisions neither.

If I think in myself, the day and week is totally fine as it is.

**Comment by admataz** [comment]
I agree totally @ifraixedes, let's just make sure people know we are just gathering input and will do our best to keep everyone involved.

**Comment by ifraixedes** [comment]
Ok, I will update this evening the form description to mention it; that has been very good point, thanks @admataz

**Comment by ifraixedes** [comment]
I updated it with the mentioned notice

**Comment by admataz** [comment]
thanks @ifraixedes

**Comment by iancrowther** [comment]
we want the community to feel like were listening and trying to progress.  A simple form gives them a voice.  no big announcements, just a simple tweet

**Comment by orliesaurus** [comment]
sticking to wednesdays
