### ISSUE TITLE
Flickr Album

### ISSUE THREAD

**Issue by tomgco** [lnug/feedback#13]
Would be nice to have a Flickr album dedicated to LNUG.

I would happily start brining my camera to the events I can attend to take photos.

Thoughts?

**Comment by ifraixedes** [comment]
My 5 cents.

I think that it wold be a good idea if somebody wants to take the responsibility of it; you may want to take it, however somebody should take it as well to avoid only have pictures in the events that you can attend and not in others.

On the other hand we could encourage to people to take pictures and send us to add to the album, however some people would like to take the responsibility is key of it.

**Comment by iancrowther** [comment]
agreed, this is an area that would need ownership.  however team photography would be great.  im sure there are some dusty cameras knocking around

**Comment by orliesaurus** [comment]
@tomgco you want ownership :P ? if not we'll keep having @jkbits1 take pics and post them to twitter (which is okay for me)

**Comment by tomgco** [comment]
@orliesaurus I will take ownership of this, as long as speakers don't mind flashes going off, @jkbits1 is more than welcome to keep posting photos on the twitters though :D

**Comment by admataz** [comment]
If we sort out some constant lighting generally - a spot or something, because it's bad in the videos too, would flashes still be necessary?

**Comment by orliesaurus** [comment]
We'll have a new venue soon P.S @iancrowther can u mail me the details of the guy that offered us his venue last time :O

**Comment by tomgco** [comment]
> If we sort out some constant lighting generally - a spot or something, because it's bad in the videos too, would flashes still be necessary?

Really depends on how powerful the projector is and if it is still legible in brighter conditions.

> We'll have a new venue soon - thus we'll see about the lights hehe P.S @iancrowther can u mail me the details of the guy that offered us his venue last time :O

EXCITE!

**Comment by iancrowther** [comment]
@tomgco is this this alive?

**Comment by iancrowther** [comment]
closed as inactive
