### ISSUE TITLE
Help us curate speakers

### ISSUE THREAD

**Issue by iancrowther** [lnug/feedback#15]
Speaking with Fintan Ryan (http://www.meetup.com/iotlondon/)

**Comment by simonmcmanus** [comment]
Like this idea. 

Alexandra Deschamps-Sonsino  (IOT London organiser) will be able to help. Let me know if you need an intro.

**Comment by iancrowther** [comment]
can you intro pls

**Comment by iancrowther** [comment]
@simonmcmanus you never intro'd

**Comment by simonmcmanus** [comment]
intro sent. Apologies for delay.

**Comment by iancrowther** [comment]
@lnug/organisers does anyone want to try and run with this?

**Comment by iancrowther** [comment]
curation is nice but a massive overhead - does anyone want to help me?

**Comment by oluoluoxenfree** [comment]
Possibly after this week, I'm surprised how much interest people have in giving feedback

**Comment by iancrowther** [comment]
@oluoluoxenfree - can you assign yourself and start putting together a plan
