### ISSUE TITLE
Triangle Stickers

### ISSUE THREAD

**Issue by iancrowther** [lnug/feedback#16]
I would love to gather some ideas for triangle stickers.

We have a contributor one for everyone who attended the hackday (Come see me on the 27th)

![img_2853](https://cloud.githubusercontent.com/assets/76060/7631899/bafa1826-fa3f-11e4-9b8c-64af5e8d8282.JPG)

**Comment by iancrowther** [comment]
@maxwellito how about one for speakers to show you have done a talk?

**Comment by maxwellito** [comment]
I'm good with it. What the logo would be? A megaphone?

**Comment by iancrowther** [comment]
could work, also maybe a microphone or speech bubble

https://brianjpankratz.files.wordpress.com/2012/11/talk.gif

**Comment by maxwellito** [comment]
Ok, any ideas for the position?
The right one is taken now. So bottom left? bottom right? left? top left? top right?

**Comment by iancrowther** [comment]
your call :-)

**Comment by maxwellito** [comment]
![official_triangle](https://cloud.githubusercontent.com/assets/1097232/7736188/007725d4-ff3a-11e4-8f88-fbde314ebea5.gif)
Bottom right, what you think?

**Comment by iancrowther** [comment]
nice

**Comment by maxwellito** [comment]
Any ideas? Things to change? Things to try?
Or maybe you want the feedback of somebody else.

**Comment by iancrowther** [comment]
we should ask speakers if they want it first, then if they do, print them

**Comment by iancrowther** [comment]
more sticker ideas? not sure tbh

**Comment by iancrowther** [comment]
@maxwellito can you prep this sticker for print?

**Comment by maxwellito** [comment]
Where shall I post the file?

**Comment by iancrowther** [comment]
um! where did they go before?

**Comment by iancrowther** [comment]
https://github.com/lnug/lnug.github.io/tree/master/assets/stickers

**Comment by iancrowther** [comment]
@maxwellito should we persue this?

**Comment by maxwellito** [comment]
No idea :( 
*(I know it's not helping)*
