### ISSUE TITLE
Coderwall Badges (via @barisbalic)

### ISSUE THREAD

**Issue by iancrowther** [lnug/feedback#17]
We should add LNUG & Nodeschool to codewall

**Comment by iancrowther** [comment]
@barisbalic - can you add some more details?

**Comment by barisbalic** [comment]
https://coderwall.com/ gives people a profile with badges, people love badges, there's lots of imagery for the nodeschool tutorials, perhaps there is some overlap that will excited The Kids:tm:

**Comment by olizilla** [comment]
Do people still coderwall?

If so, @substack did a load of great nodeshool workshopper badges a while back... they'd work nice.

**Comment by barisbalic** [comment]
Dunno, don't care about it either way just mentioned in passing because
people like pretty.
