### ISSUE TITLE
Node Q&A Panel

### ISSUE THREAD

**Issue by iancrowther** [lnug/feedback#18]
I would like to put together a 4 person Q&A panel for LNUG.  This could be for the whole night or just be for a couple of speaker slots

**Comment by iancrowther** [comment]
Do we have any potential questions?  what made you adopt, what made you not adopt, what went well in moving to node? etc

**Comment by web-bert** [comment]
Should you use Node for everything backend or just as a presentation layer that consumes APIs? Pros/Cons

**Comment by iancrowther** [comment]
closed in favor of an enterprise event
