### ISSUE TITLE
Xmas Party!!!

### ISSUE THREAD

**Issue by iancrowther** [lnug/feedback#28]
```
*News Flash*

There will be no LNUG in December :-( 

```

``` 
*Update*

There will be a christmas party - woooo hoooo

```

**Comment by julienbrunuk** [comment]
Yes Yes Yes! Do you want to send a Doodle around!?

**Comment by iancrowther** [comment]
@julienbrunuk will you organise this? :-)

**Comment by oluoluoxenfree** [comment]
Be willing to help :)

**Comment by iancrowther** [comment]
w00t

**Comment by julienbrunuk** [comment]
There *will* be a christmas party. Details will be provided very, very shortly.

**Comment by iancrowther** [comment]
@oluoluoxenfree ask @julienbrunuk if he needs any help? he is taking the lead on this
