### ISSUE TITLE
do we want to be on meetup

### ISSUE THREAD

**Issue by iancrowther** [lnug/feedback#31]
can we be on meetup without using their ticketing system etc

**Comment by ifraixedes** [comment]
No, for me

**Comment by iancrowther** [comment]
if were just using it to gain reach?  can we jsut promote event with it and ignore the other features?

**Comment by ifraixedes** [comment]
That's true, however that depends of the budget, which you know better than almost everybody.

Remind you that @barcelona-js left meetup, however it had to return back to use due they lost quite mass of attendees due people looked for the event in meetup than Google, crazy?

**Comment by iancrowther** [comment]
will add us
