### ISSUE TITLE
brand / skin ti.to

### ISSUE THREAD

**Issue by iancrowther** [lnug/feedback#33]
this is part of the rebranding

**Comment by iancrowther** [comment]
mentioned in #36

**Comment by iancrowther** [comment]
@maxwellito bump

**Comment by maxwellito** [comment]
Are you talking about this page? https://ti.to/lnug

**Comment by iancrowther** [comment]
yep.

I want get a unified brand.  inc the slides, website, services such as twitter, ti.to etc

**Comment by maxwellito** [comment]
Ok, do we have something to start with (existing slides, color scheme...)?
Otherwise I can start to make a repo with everything

**Comment by iancrowther** [comment]
slides can be found here https://swipe.to/2657cp

When I arrive, I put up a welcome slide with basic info.  I would love to have the logo animated in some way.

**Comment by iancrowther** [comment]
Other branding would come from the website. 

There are no brand guidelines yet so there is no brand consistancy accross services.  This guide would be a great starting point to work from.

The gravatar etc with help.
