### ISSUE TITLE
remove "this month" from website

### ISSUE THREAD

**Issue by iancrowther** [lnug/feedback#34]
Its redundant

**Comment by web-bert** [comment]
This month takes you back to the homepage, do you want to remove the home link?

**Comment by iancrowther** [comment]
what do you think? maybe add some css to highlight the selected page?

**Comment by iancrowther** [comment]
@benbyford @maxwellito what do you guys think?

**Comment by web-bert** [comment]
Yeah I think a highlight would help

**Comment by iancrowther** [comment]
@web-bert go for it :-)

**Comment by benbyford** [comment]
true, its not obvious that your on the homepage as that link isn't highlighted in any way

**Comment by iancrowther** [comment]
@simonmcmanus can u action this and close

**Comment by iancrowther** [comment]
so whats the deal si? shoudl we push PR's or are you doing some new magic?

**Comment by iancrowther** [comment]
@simonmcmanus bump
