### ISSUE TITLE
Consistant Branding

### ISSUE THREAD

**Issue by iancrowther** [lnug/feedback#36]
It would be awesome to start with a UX review on the website and document the Information Architecture.  Followed by the maillist etc

**Comment by iancrowther** [comment]
@benbyford - what do you need to know?

**Comment by iancrowther** [comment]
Need to redo the slides & ti.to also

**Comment by iancrowther** [comment]
https://github.com/lnug/feedback/issues/33

**Comment by iancrowther** [comment]
https://github.com/lnug/feedback/issues/24

**Comment by simonmcmanus** [comment]
@iancrowther @maxwellito @clarkie  - What is outstanding on this? Can it be closed?
