### ISSUE TITLE
Website fonts cors

### ISSUE THREAD

**Issue by iancrowther** [lnug/feedback#49]
```
Font from origin 'http://fonts.gstatic.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://lnug.org' is therefore not allowed access.
```

**Comment by orliesaurus** [comment]
screenshot? cannot reproduce

**Comment by iancrowther** [comment]
<img width="1280" alt="screen shot 2015-07-15 at 11 40 03" src="https://cloud.githubusercontent.com/assets/76060/8696679/5a72bc4c-2ae6-11e5-8454-1c6501f8cb6a.png">

See the debug window

**Comment by toboid** [comment]
I can't re-create. I've tried chrome 43 on Windows and Ubuntu and the 3 calls to fonts.gstatic.com are all successful

**Comment by iancrowther** [comment]
I bet it's as blocker!!!

**Comment by iancrowther** [comment]
yep ad blocker.. d'oh!
