### ISSUE TITLE
create transparent sponsor tiles for ti.to's benefit

### ISSUE THREAD

**Issue by iancrowther** [lnug/feedback#51]

**Comment by iancrowther** [comment]
hey @maxwellito did you get round to this?

**Comment by iancrowther** [comment]
@maxwellito should we be concerned with this?

**Comment by jkbits1** [comment]
I think the white tiles look fine

**Comment by maxwellito** [comment]
I created something to make transparent black logos with white background pictures : http://maxwellito.github.io/ghoster/

Otherwise tell me which one to transform :) (with resolutions, shall we store them into a repo for common shared assets across LNUG?)

**Comment by iancrowther** [comment]
@maxwellito - just wow!

**Comment by maxwellito** [comment]
It's simple but very handy :)
If you want any idea of improvement, please open a issue.

**Comment by iancrowther** [comment]
will do

**Comment by iancrowther** [comment]
ok feature request.  I would like to specify dimentions and generate a horizontally and vertically aligned tile

**Comment by iancrowther** [comment]
just used this tool again!! super handy
