### ISSUE TITLE
create a graphic we can use for gravatar

### ISSUE THREAD

**Issue by iancrowther** [lnug/feedback#52]
We have number of services we use the LNUG email with.  it would be great to setup Gravatar.

**Comment by iancrowther** [comment]
cc' @maxwellito @tancredi @benbyford

**Comment by iancrowther** [comment]
can you take a look at this please

**Comment by maxwellito** [comment]
Can you share the email addresses please?
I'll set the LNUG logo to Gravatar

**Comment by iancrowther** [comment]
contact@lnug.org is the one we use for everything

**Comment by iancrowther** [comment]
I think I set it up, just needs the graphic

**Comment by maxwellito** [comment]
![avatar_600](https://cloud.githubusercontent.com/assets/1097232/10715650/ded6814c-7b15-11e5-8ea7-be2866908a3f.png)
Here is the LNUG avatar in 600px.
I made an Ai file if required. Might be useful for future usage. If you want it in a repo somewhere, tell me and I'll make a PR

**Comment by iancrowther** [comment]
amaze - please create an assets directory https://github.com/lnug/feedback so that these assets are easy for people to find and not lost in the website repo

**Comment by iancrowther** [comment]
gravatar is alive :-)

thanks @maxwellito
