### ISSUE TITLE
one click tickets

### ISSUE THREAD

**Issue by gajjargaurav** [lnug/feedback#55]
having attended few LNUG monthly meetups, I now intend to regularly attend LNUG every month and filling out details on ti.to every month to get a ticket is repetitive . It would be much better if I can just confirm that I am coming to next event by a click of a button and get a ticket

**Comment by iancrowther** [comment]
Interesting, that's probably one to bubble up to ti.to

@jkbits1 does ti.to have anything like this in the pipeline?

**Comment by admataz** [comment]
Filling two fields with name and email address is too repetitive? Personally I think ti.to does a pretty good job at keeping things as simple as possible from the end user perspective. But I suppose if we really wanted to get fancy here, we could take a leaf from this month's talk by @jdnash and apply some tokenization  to our registered users, and provide a one-click link from the email to a confirmation/registration with ti.to... Would you up for developing something like  that @gajjargaurav?

**Comment by gajjargaurav** [comment]
It sure sounds interesting to work on. It's not just the login, they also request for twitter account and few additional info optionally every time.

**Comment by gajjargaurav** [comment]
@iancrowther, @admataz I had a quick look at the ti.to api. They do not provide any write endpoints just yet so you can't add attendees to the event programmatically just yet. However I spoke to their support team and they said it is high on their priority list and as soon as it is available, I can work on it but until then I am afraid it is blocked.

**Comment by admataz** [comment]
Hi @gajjargaurav  - thanks for looking into it - I'll take it off the hotlist for the time being... Hopefully we can do something with it in the future

**Comment by gajjargaurav** [comment]
Hello @admataz , I am keeping an eye on this one and as soon as I see it unblocked I will work on it

**Comment by iancrowther** [comment]
im closing this as its a ti.to product feature, not an lnug fix
