### ISSUE TITLE
create an 'attendees' list in twitter

### ISSUE THREAD

**Issue by admataz** [lnug/feedback#58]
We ask for twitter handles in the ti.to registration - not sure where this currently goes, but it would be nice to use this data to create a public Twitter List of attendees. Would be good to be able to follow all our community in one place. Related to #42 if we are going to automate this.

**Comment by iancrowther** [comment]
totally agree.  

new repo with readme?

**Comment by jkbits1** [comment]
@admataz sounds good

**Comment by mikeljames** [comment]
Hey guys have you made a start on this? Got an idea to try out JAWS https://github.com/jaws-framework/JAWS with this it looks this would be a perfect fit for it. Let me know if you haven't started already and what you think we need. 

So its a webhook from ti.to that then takes the attendee @handle in the signup to add them to a specific list on twitter. each event will have its own attendee list on twitter.

**Comment by iancrowther** [comment]
@jkbits1 has this started? I don't think it has to any degree.  

@mikeljames I think this would be fantastic, we can even do a talk on how it was built, how to contribute and how it could be used for spin-offs.

win win win :-)

**Comment by mikeljames** [comment]
Sounds good! I'll do my best to get it ready for the next meetup :D

**Comment by mikeljames** [comment]
I've setup my own ti.to account and testing with that api. but eventually I'll need to use the lnugs api keys for ti.to and twitter. 

Also does lnug have its own aws account?

**Comment by iancrowther** [comment]
Come to think of it no! Would prefer digital ocean or heroku or any that will give us some free / cheap space

**Comment by iancrowther** [comment]
I think rackspace may have some community options

**Comment by admataz** [comment]
I'm guessing the [JAWS framework](https://github.com/jaws-framework/JAWS) requires the service to be hosted on AWS, in which case Heroku and Rackspace won't work for @mikeljames's suggestion. Would that be a blocker @iancrowther? I would also think a solution that is not provider dependent is better for LNUG and the kind of spin-offs you envisage...  but wouldn't want to put you off trying this if you think JAWS  is a good fit over something more flexible and generic.

**Comment by iancrowther** [comment]
@mikeljames @admataz gotcha, I'll actually read the readme this time ;-)

JAWS says cheap apps, so I'm intrigued to know how it stacks up against the alternatives.  Do they have a comparison chart anywhere which could be shared?

**Comment by admataz** [comment]
my other 2p - is that a full framework like JAWS _seems_ like overkill for processing and relaying a simple web hook request to twitter - one could surely do that with a couple of simple modules using [request](https://github.com/request/request)  -  but the other side of me thinks why the hell not - if AWS is something that's worth experimenting with.

**Comment by iancrowther** [comment]
AWS for me has always been an enterprise solution, however if they are now reaching into our price bands, its worth investigating.

**Comment by mikeljames** [comment]
Hey! Yeah so if you open a new aws account you'll get 1 year free with AWS plus with lambda on AWS you pay for what you actually use. So no requests == no bills. You pay for the amount of time your lambda functions run for. 

Here's a price list: https://aws.amazon.com/lambda/pricing/

Yeah well I thought maybe the fact we could process these webhooks from ti.to via aws in a non server environment would be pretty cool.

Its not really a full framework its just a wrapper for deploying code to lambda. My argument is that running a full server to just process a webhook seems overkill to me.

**Comment by iancrowther** [comment]
@mikeljames - thanks for the update, no complaints here.  can you setup an account using contact@lnug.org and ill verify the address if req'd.

cant argue with £0 and i agree with the overkill sentiment.

**Comment by mikeljames** [comment]
@iancrowther cool, I've also just been discussing this with @clarkie he's also suggested having a look at hook.io. 

If I build it in the right way we could deploy it to both and afterwards compare the two.

**Comment by ifraixedes** [comment]
Hi guys, I thought that this package https://github.com/node-hocus-pocus/thaumaturgy may be useful, although you may already be aware of it.

**Comment by mikeljames** [comment]
:) Thanks @ifraixedes  I'll have a look.

**Comment by iancrowther** [comment]
@mikeljames - hows this coming along?

**Comment by mikeljames** [comment]
Hey @iancrowther I've been having a play with hook.io after I had a chat with @clarkie on gitter. So going to go with hook.io for now. Been on holiday and started a new job so been pretty busy! :D

**Comment by iancrowther** [comment]
np - can you assign yourself to this any own the issue :-)

**Comment by mikeljames** [comment]
@iancrowther it appears I do not have permissions to do that :S

**Comment by iancrowther** [comment]
oh right! ive added you as a contributor..

how can i make these issues public? any ideas?

**Comment by iancrowther** [comment]
that might explain why no-one is picking up issues!

**Comment by iancrowther** [comment]
hey @mikeljames - hows this progressing?

**Comment by mikeljames** [comment]
@iancrowther it's a WIP =)

**Comment by mikeljames** [comment]
@iancrowther it's a WIP I should have some more time very soon =)

**Comment by iancrowther** [comment]
@mikeljames - visit https://github.com/lnug and accept your invite

then you can assign yourself this issue

**Comment by mikeljames** [comment]
Hey @iancrowther I'm still unable to assign myself... Permissions related?
![image](https://cloud.githubusercontent.com/assets/2983327/11700024/41376f32-9ebf-11e5-93f7-cbe6b871370f.png)

**Comment by iancrowther** [comment]
@mikeljames have you joined the collaborators team?

**Comment by iancrowther** [comment]
@mikeljames - yep! try now

**Comment by admataz** [comment]
hi guys. Just wondering  - has anyone had a chance to look into any of the interesting ideas discussed earlier in the thread?

**Comment by export-mike** [comment]
Yeah been playing with hook.io over the weekend.

**Comment by export-mike** [comment]
meetup.com have an api for this?

**Comment by iancrowther** [comment]
not sure, what do the docs say?

**Comment by admataz** [comment]
this was a cool idea - but I think it's dead for now
