### ISSUE TITLE
google search - "lnug lanyrd"

### ISSUE THREAD

**Issue by simonmcmanus** [lnug/feedback#59]
returns the first link as: 

http://lanyrd.com/series/lnug/

The most recent event listed is July 2014. It makes it look like the event has not been running for a year. Or at least that we have not used lanyrd for a year. 

Have we changed the way we tag the event in lanyrd since then? Im guessing it wont be too difficult to fix.

**Comment by iancrowther** [comment]
Hi @massimilianomura,

1) is this months ready?
2) can you investigate?

**Comment by simonmcmanus** [comment]
I should also mention I'm going to try to auto generate the lanyrd url (on the website archive) from the GitHub milestone. It will confirm the url returns a 200 before using the url for the href. This does mean we will need to publish the lanyrd event before updating the website. 

Does that sound ok?

**Comment by jkbits1** [comment]
@iancrowther this month's lanyrd is done. Did you manage to make that doc on creating the lanyrd page?

**Comment by jkbits1** [comment]
I can't see an obvious difference between the events on the list and those omitted. The hash tag becomes lowercase in Sept 14. Those earlier events have a link "In the London Node.js User Group Meetup series", but following that doesn't provide anything useful.

**Comment by iancrowther** [comment]
what action is to be taken here?

**Comment by iancrowther** [comment]
@jkbits1 @simonmcmanus bump

**Comment by iancrowther** [comment]
@jkbits1 or @MassimilianoMura can you contact Lanyrd support and ask them?

**Comment by jkbits1** [comment]
@iancrowther good idea

**Comment by iancrowther** [comment]
ok so this is to do with claims i think.

we have our events listed as: 

- http://lanyrd.com/series/lnug/
- http://lanyrd.com/guides/lnug-events/

previously events were climed by the twitter account @iancrowther as we did not have @lnugorg setup

**Comment by iancrowther** [comment]
also the url structure is defferent

someone needs to back trackthrough and try to bring things inline and update the instructions.

**Comment by iancrowther** [comment]
whoever takes ownership of lanyrd should take on this
