### ISSUE TITLE
reach out to related-meetups

### ISSUE THREAD

**Issue by iancrowther** [lnug/feedback#61]
We should send a tweet to our related-meetups to ask their organiser to get in touch (contact@lnug.org) so we can PR them.

@trevorah - can you schedule a tweet for this?

**Comment by iancrowther** [comment]
@trevorah did this go out?

**Comment by trevorah** [comment]
Yeah, ages ago: https://twitter.com/LNUGorg/status/631027780826693632

**Comment by iancrowther** [comment]
awesome, ty
