### ISSUE TITLE
Add event start time to landing page

### ISSUE THREAD

**Issue by olizilla** [lnug/feedback#68]
As an irregular attendee I can't easily find the start time for LNUG.

Obvs, everyone should have it tatoo'd on their arm, but looking for it on my tito ticket or the website hasn't worked.

Lanyard, has a start time for LNUG, but it's listed as 4:30.
<img width="634" alt="screenshot 2015-09-23 17 47 05" src="https://cloud.githubusercontent.com/assets/58871/10051834/7ae16e4e-621b-11e5-9bab-e787c21ac504.png">

The tito ticket homepage has it, discretely in the additional info section:

<img width="922" alt="screenshot 2015-09-23 17 47 48" src="https://cloud.githubusercontent.com/assets/58871/10051827/75ff9f40-621b-11e5-8b22-b0e14bf34968.png">

I vote we add it in big to the lnug.org website.

**Comment by admataz** [comment]
@olizilla agree. noted. it's 6.30 for 7 start btw..

**Comment by iancrowther** [comment]
agreed

**Comment by simonmcmanus** [comment]
@olizilla - its now nice and big on lnug.org, are you happy to close?

**Comment by olizilla** [comment]
Super nice! :+1: 
<img width="808" alt="screenshot 2015-12-14 09 58 58" src="https://cloud.githubusercontent.com/assets/58871/11777966/5fa65964-a249-11e5-83b9-635e91311873.png">
