### ISSUE TITLE
Global video vault

### ISSUE THREAD

**Issue by iancrowther** [lnug/feedback#7]
@rosskukulinski @bencevans @basicallydan

where do you put your videos? we put them on youtube?

I'm wondering if simple links to each others video vault would do for now.. that way we post to our preferred channels as usual, in the usual format with no admin

thoughts?

**Comment by rosskukulinski** [comment]
I've been putting them up on up on my personal YouTube: https://www.youtube.com/playlist?list=PL-haG1KBddyv9gtC9TZFGwJA44SZ0ULOj

I'm thinking just having a quasi-organized README.md with topics/authors/talk title/link should be fine to get us started.

**Comment by iancrowther** [comment]
ok - we have an LNUG youtube channel which you can just link to :-) simples
