### ISSUE TITLE
show a schedule of upcoming events

### ISSUE THREAD

**Issue by iancrowther** [lnug/feedback#75]

**Comment by iancrowther** [comment]
@simonmcmanus @maxwellito this came in as feedback from NottsJS but is relevant here

**Comment by simonmcmanus** [comment]
We could pull in all the milestones setup in github I guess, that would give a list of the next few events. 

Would need to think about where in the UI it sits.  Not gonna look at this till after the redesign is out.

**Comment by iancrowther** [comment]
fair enough

**Comment by iancrowther** [comment]
https://github.com/lnug/lnug.github.io/issues/84
