### ISSUE TITLE
Event Loop Video

### ISSUE THREAD

**Issue by iancrowther** [lnug/feedback#77]
We have been asked to update this video.  IF we dont have time, we should remove it.

https://www.youtube.com/watch?v=2xTakP0xKQw&google_comment_id=z12telxr3pqfyprnq23gxrcirxyfetun1&google_view_type#gpluscomments

**Comment by iancrowther** [comment]
@alanshaw - fancy it?

**Comment by alanshaw** [comment]
I think there are better resources for this - https://www.youtube.com/watch?v=8aGhZQkoFbQ

**Comment by iancrowther** [comment]
agreed - i'll delete the crazy vid then
