### ISSUE TITLE
Help improve the slide skin

### ISSUE THREAD

**Issue by iancrowther** [lnug/feedback#83]
@maxwellito can you help me put together a slide template using the new logo?

**Comment by iancrowther** [comment]
slides are now in resources/slides

https://github.com/lnug/resources/tree/master/slides

they are build using node, rendered using webkit so we can got to town here

**Comment by maxwellito** [comment]
I didn't managed to install `deck`. The install keep failing :-S You don't have something else to allow me to see and edit the slides?

**Comment by iancrowther** [comment]
@davidmarkclements can you pitch in here, being the author of zee deck?

**Comment by iancrowther** [comment]
see https://github.com/nearform/deck

**Comment by davidmarkclements** [comment]
hey @maxwellito can you tell me a bit about your setup

1) OS
2) node version

can you also show me the install fail logs

**Comment by maxwellito** [comment]
It's a silly issue of permission while installing `electron-prebuilt`. It cannot rename the folder... I'll see how to sort this out later. 

PS: I ran this with sudo rights

**Comment by iancrowther** [comment]
pro tip - "the base style is flexbox"

@davidmarkclements any tips or gotchas we need to know about?
