### ISSUE TITLE
Design LNUG Sticker for 2016 

### ISSUE THREAD

**Issue by iancrowther** [lnug/feedback#84]
is everyone happy with the sticker?

https://github.com/lnug/lnug.github.io/tree/master/assets/stickers

![image](https://cloud.githubusercontent.com/assets/76060/11341331/fae8aacc-91f9-11e5-8049-003881a395d3.png)

we have some alternative suggestions

![image](https://cloud.githubusercontent.com/assets/76060/11341348/1217ac0c-91fa-11e5-970a-b1b7ca8eddd3.png)

**Comment by maxwellito** [comment]
Looks gorgeous!! <3

**Comment by iancrowther** [comment]
Yes yes, I'm sure it was you who brought it up 😉

**Comment by iancrowther** [comment]
@lnug/organisers bump?

**Comment by iancrowther** [comment]
@maxwellito - can you do a variation of the sticker for 2016

**Comment by iancrowther** [comment]
@simonmcmanus @maxwellito we seem to have lost the sticker assets?

**Comment by iancrowther** [comment]
2016 sticker sorted

https://github.com/lnug/resources/blob/master/stickers/official/2016/official_hex.png

**Comment by rdquintas** [comment]
Love it.
I want one!!

**Comment by iancrowther** [comment]
they wont be ready for this month.. they'll come about 2 days after!
