### ISSUE TITLE
ti.to sponsors look untidy

### ISSUE THREAD

**Issue by jkbits1** [lnug/feedback#86]
Also, the sponsorship tiers (gold, silver etc) don't stand out visually enough so the meaning isn't clear

**Comment by iancrowther** [comment]
I have an PR for transparent images

https://github.com/lnug/lnug.github.io/pull/60

this will fix the "untidy"

**Comment by iancrowther** [comment]
can you test & merge @jkbits1

**Comment by iancrowther** [comment]
Agreed with the visuals, what do you suggest?

**Comment by jkbits1** [comment]
@iancrowther - merge done and transparents included on tito. 

Within the constraints of markdown and the css theme provided (which as I understand it, means we can't tweak the css as usual), I've made an attempt to give a clearer repeating pattern or rhythm to the sponsor divisions. I've made small adjustments to some logo sizes, so the proportions work better.

As the consensus seems to be for transparent images (I'm not totally convinced given the tito bkg colour myself but can see the reasoning for it), when we have those for yld and artificial labs, that will increase consistency.

As it is now, it looks reasonable and in line with the main site

**Comment by iancrowther** [comment]
"I've made an attempt to give a clearer repeating pattern or rhythm to the sponsor divisions" - cool

**Comment by iancrowther** [comment]
"I've made small adjustments to some logo sizes, so the proportions work better." - This concerns me a little, did you edit the physical asset or use css?

We really should be using the same asset everywhere for consistancy and maintainability

**Comment by iancrowther** [comment]
"I'm not totally convinced given the tito bkg colour myself but can see the reasoning for it" - im in agreement, but its about a single asset

**Comment by iancrowther** [comment]
@jkbits1 see https://github.com/lnug/lnug.github.io/pull/62 for the missing images

**Comment by jkbits1** [comment]
size adjustments made through styling

revised images are applied automatically, no edit needed
