### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by zsid** [lnug/feedback#88]
I really enjoyed the lnug meetup tonight. Well done guys! 

A few things to note:

As someone who wants to learn Node (I came with a few friends who were also beginners), it will be great if there were a few suggestions where someone could start from scratch learning Node and become a master. I know you talked about Nodeschool but it might be good to point out a few tutorials in there. For example: 
- Beginners section
- Intermediate section
- Advanced section

Even opinions what you will expect someone at a beginner level, an intermediate level and advanced concepts.  Maybe the speakers can briefly talk about how they have levelled up :smile: 

In terms of presentations, maybe rather than doing high level overviews of different concepts - i.e. Using docker, might be better to focus on a very specific example and do a quick demo and kinda walkthrough, focusing on a specific feature or task. Another idea can be talking about your favourite node module and why you love it so much or even a hidden node module that you have come across by accident and do a demo etc.

Thanks
Zhivko

**Comment by iancrowther** [comment]
Thanks for your feedback, it really helps.

"it will be great if there were a few suggestions where someone could start from scratch learning Node and become a master" - would a section / page on the website be enough? then we can point to that resource?

**Comment by iancrowther** [comment]
"Maybe the speakers can briefly talk about how they have levelled up" - im reluctant to interfere with a talk.

**Comment by iancrowther** [comment]
"might be better to focus on a very specific example and do a quick demo and kinda walkthrough" - This kind of talk would be very welcome.

Would you fancy doing one?  It does not have to be super advanced, afterall your target audience is beginner.

**Comment by zsid** [comment]
Hi Ian,

Thanks for the prompt response.

------
 "it will be great if there were a few suggestions where someone could start from scratch learning Node    and become a master" - would a section / page on the website be enough? then we can point to that resource?

A section/page will be more than enough. Sounds great.
------

"might be better to focus on a very specific example and do a quick demo and kinda walkthrough" - This kind of talk would be very welcome.
"Would you fancy doing one? It does not have to be super advanced, after all your target audience is beginner."

Thanks for the proposal. Sounds great. When will be a good time? You mentioned last night that all slots were taken in January. Will February be a good time?

**Comment by iancrowther** [comment]
"A section/page, pointing to the specific resource will be more than enough. Thank you." - ok raise this as a seperate issue and one of the team will pick it up.

**Comment by iancrowther** [comment]
github.com/lnug/speakers - drop us a proposal here, then we can see if its better suited to feb or march

I for one will be happy to get an entry level talk onthe roster

**Comment by zsid** [comment]
Hi Ian,

Thank you, I will create a new issue with regards to the material. I have also submit a proposal to the speakers section.

Thanks,
Zhivko
