### ISSUE TITLE
Help us curate speakers

### ISSUE THREAD

**Issue by iancrowther** [lnug/feedback#92]
As part of the event planning, we could do with some help planning speakers and inviting guests

**Comment by iancrowther** [comment]
@oluoluoxenfree - please can you assign yourself and share the P-L-A-N :-)

**Comment by oluoluoxenfree** [comment]
Sure, sorry for the slow response!

**Comment by iteles** [comment]
@oluoluoxenfree You're _everywhere_ :wink:

**Comment by oluoluoxenfree** [comment]
@iteles I do try!

Going to base it off of this: https://github.com/charmCityJs/talks/wiki/Curating-Talks

**Comment by oluoluoxenfree** [comment]
Add just a glob of thoughts before I forget:

* Nominations for people to contact (talks you've seen, or people you know who could give a talk on x) appreciated, in these cases public contact details (i.e. Twitter) or a personal introduction would be best.

* Would be best to either switch up curators or have a few people interested in it to keep numbers up.

* Would be good to have a document or pack for nominated speakers so they aren't confused about what LNUG is or what is expected of them (may already exist).

**Comment by iancrowther** [comment]
"Nominations" - i love this idea, do you see this being don provately or publically?  How would this work?
do we want to create/use a crm?

"curators" - your on this :-) you'll have to keep askign folks to get involved I suspect

"document or pack for nominated speakers' - we can update the speakers [README.MD](https://github.com/lnug/speakers/blob/master/README.md) what do you think? does it need work? if so can you submit a PR or notes?

"launching pad" - we absolutly encourage new speakers, I think we one have in Feb.  The talk is aimed at beginnners and is by a new speaker :-)  we should be clear that everyone is welcome though.  where on the site would you not this?

"find speakers" - I have a speakers pipeline in my crm to manage this, we should use/modify this 

are you happy to take a more active role here?

**Comment by admataz** [comment]
+1 on all the above  - I think it's a great approach. 

Related, maybe - I know it's been hinted at before in a couple discussions about potential IoT and Enterprise focused meetups - would it be good to think also about occasional special topic meetups - which may also be a reflection of a curator's expertise  - so an evening of talks on DB's, or Front End, or Hardware, or whatever - where all 3 talks of an evening revolve around a particular aspect of node.js?

I think it could prove an interesting way to draw in a broader community to the meetups.

**Comment by iancrowther** [comment]
agreed - this needs ownership though

**Comment by oluoluoxenfree** [comment]
I'll do this later today, and yes I don't mind taking ownership, but I migh thave to take suggestions for topics at the moment re: specialisations!

**Comment by iancrowther** [comment]
Performance 
Testing
Beginners
IOT 
Realtime
Etc

**Comment by oluoluoxenfree** [comment]
A CRM would be great, I think privately makes more sense as people would probably feel a bit hounded if it was public, but any other thoughts?

I'm fine curating + taking a more active role, sorry for the slowness!

**Comment by oluoluoxenfree** [comment]
I think the README needs more resources and explicitly stating it's fine for beginners to try.

Could you include something about recommending speakers in one of the newsletters? Or regularly maybe?

**Comment by admataz** [comment]
Hi Olu  - yes - good idea, I'd be happy to add something in the newsletter, as a fixture that explains the approach - there's an issue for newsgathering: #96  - if you can add some description there.  

Do we need a full blown CRM? Or can we handle it as a private repos/ issue list in github? (I'm in favour of not spreading across too many platforms if we can help it). If we want to keep nominations private I assume we could create a way for public submissions (via the website and github API) to create issues.

**Comment by clarkie** [comment]
@admataz and @oluoluoxenfree we talked about a 'buddy' system at our meeting the other day for speakers (if they want it). This would hopefully help encourage first time speakers as we can buddy them up with someone who may have spoken on a similar subject to help with putting together their presentation, etc.

**Comment by admataz** [comment]
@clarkie yes - let's write up an approach that will encourage new speakers that and we can communicate in the newsletter, add to the readme, and maybe announce at the next meetup - the underlying principle being: here are some ways we would like to support speakers.  I'll create an issue in the planning repos

**Comment by iteles** [comment]
This (somewhat abandoned) site is also a good link for beginner speakers: http://weareallaweso.me/

**Comment by admataz** [comment]
Great ideas here but it seems effort on this issue has been abandoned - tagging for future reference and closing

**Comment by jkbits1** [comment]
@admataz just a final thought on this. I met with speakers in 2016 for a chat about their upcoming talks and it was useful. Something along these lines doesn't have to be too intensive for either lnug organisers or speakers

**Comment by admataz** [comment]
@jkbits1  - yes I agree that we should continue to offer speakers support and feedback wherever possible and practical. In terms of formalising that approach we have this issue: https://github.com/lnug/planning/issues/91 in planning - which is still open.
