### ISSUE TITLE
Confirmation Email

### ISSUE THREAD

**Issue by FinnCavanagh** [lnug/feedback#95]
Hey guys, 

I'm excited to come along to my first meetup on 27th. I'm coming to coding from marketing and just thought I would suggest adding a link to the event in the confirmation email, so it's really easy to share with others. The easier you make it to share etc ... 

Finn

**Comment by admataz** [comment]
Hi Finn - thanks for the feedback

@jkbits1  - I think you are the person for the Ti.to confirmation emails?

**Comment by iancrowther** [comment]
hey @FinnCavanagh 

thanks for the feedback

**Comment by jkbits1** [comment]
@FinnCavanagh great idea, done. Thanks very much for the suggestion :+1:  we look forward to seeing you at the event. 

We'd be very glad to hear more suggestions from you
