### ISSUE TITLE
Newsletter March 2016 - newsgathering

### ISSUE THREAD

**Issue by admataz** [lnug/feedback#98]
Every month we send out a newsletter or two to all our members. If you have something to add or share that you want to get out there - put it here.

Keep it node.js related (releases, node.js in the wild, meetups, blog post links.. stories, jokes, projects,.)
Keep it London related. (SF is cool y'all but we are here.)
Keep it community related. (That's about you and the people around you using node.js)
Oh, and it's not a jobs board, so don't even try.

**Comment by iancrowther** [comment]
https://nodejs.org/en/blog/vulnerability/february-2016-security-releases/
