### ISSUE TITLE
Some suggestions to celebrate the 50th LNUG session

### ISSUE THREAD

**Issue by rdquintas** [lnug/feedback#99]
Hi guys,
here's some suggestions to make the 50th LNUG event, even more special.

Maybe some of them are a little bit far out.... but who knows ?
:smile: 

- hire a DJ or band with some funky music
- extend the event (starting earlier and ending later)
- invite a "guest star". Someone that had a fundamental role on the birth of Node, to say a few words and talk about new directions
- make slides with funy stats (stuff like: how many pizzas were eaten since we stared ? how many litters of beer ? how many hours of talks ? etc...
- show slides with some highlights  (we started with XXX atendees, but now we have on average YYY)
- make a small video with the best moments (or try the same with slides if no video available)
- buy a cake and sing happy birthday
- distribute a special badge/sticker for the occasion 
- offer a supa-dupa special prize

**Comment by iancrowther** [comment]
superb suggestions.. really superb.. noted

**Comment by iancrowther** [comment]
- dj - no
- extend the event - that's the pub :-)
- guest - invited
- slides - in motion!
- video - no budget :-(
- cakes (maybe!)
- sticker (maybe!)
- special prize - suggestions?

**Comment by rdquintas** [comment]
- a shiny new Apple MacBook Pro 15'' Retina i7-2,8GHz | 16GB | 1TB
- if not possible then a bottle of Veuve Clicquot Brut NV Champagne
- if not possible, how about something from Makersacademy
- if not possible, how about something from the other sponsors (training perhaps)

**Comment by rdquintas** [comment]
How a about a "day with the pros" or something like that.
I mean, the sponsors could invite you to spend a day at their offices and during that day you would be involved on a particular project - and see how the pros work.
Live.
;o)

**Comment by rdquintas** [comment]
Ask a designer to create a really crazy-special-funny-big-sticker for the occasion.
And then create a very limited edition, making it really exclusive and special.

**Comment by rdquintas** [comment]
Or print the LNUG logo on a very crazy object
Check here
http://www.lps.promoideas.info/

or here
http://www.londonprintservice.com/products

**Comment by iancrowther** [comment]
lol - awesome.. ill see what I can muster.. am a bit tied up atm though

**Comment by simonmcmanus** [comment]
🍰
